-- Generated by Mocodo 4.3.3

CREATE TABLE ACTIVITY_SESSION (
  PRIMARY KEY (session_id),
  session_id      VARCHAR(42) NOT NULL,
  start_at        VARCHAR(42),
  end_at          VARCHAR(42),
  is_open_tail    VARCHAR(42),
  source_revision VARCHAR(42),
  user_id         VARCHAR(42) NOT NULL
);

CREATE TABLE AVATAR (
  PRIMARY KEY (avatar_id),
  avatar_id           VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE AVATAR_MEMO (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  avatar_id VARCHAR(42) NOT NULL
);

CREATE TABLE AVATAR_TAG (
  PRIMARY KEY (tag),
  tag   VARCHAR(42) NOT NULL,
  color VARCHAR(42)
);

CREATE TABLE FAVORITE_AVATAR (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  avatar_id  VARCHAR(42) NOT NULL
);

CREATE TABLE FAVORITE_FRIEND (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42)
);

CREATE TABLE FAVORITE_WORLD (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42) NOT NULL
);

CREATE TABLE FAV_FRIEND_OF (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE FEED_AVATAR (
  PRIMARY KEY (id),
  id                                 VARCHAR(42) NOT NULL,
  created_at                         VARCHAR(42),
  owner_id                           VARCHAR(42),
  avatar_name                        VARCHAR(42),
  current_avatar_image_url           VARCHAR(42),
  current_avatar_thumbnail_image_url VARCHAR(42)
);

CREATE TABLE FEED_BIO (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  bio          VARCHAR(42),
  previous_bio VARCHAR(42)
);

CREATE TABLE FEED_GPS (
  PRIMARY KEY (id),
  id                VARCHAR(42) NOT NULL,
  created_at        VARCHAR(42),
  location          VARCHAR(42),
  world_name        VARCHAR(42),
  previous_location VARCHAR(42),
  time              VARCHAR(42),
  group_name        VARCHAR(42)
);

CREATE TABLE FEED_ONLINE_OFFLINE (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  type       VARCHAR(42),
  location   VARCHAR(42),
  world_name VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42)
);

CREATE TABLE FEED_STATUS (
  PRIMARY KEY (id),
  id                          VARCHAR(42) NOT NULL,
  created_at                  VARCHAR(42),
  status                      VARCHAR(42),
  status_description          VARCHAR(42),
  previous_status             VARCHAR(42),
  previous_status_description VARCHAR(42)
);

CREATE TABLE FRIEND_LOG_HISTORY (
  PRIMARY KEY (id),
  id                    VARCHAR(42) NOT NULL,
  created_at            VARCHAR(42),
  type                  VARCHAR(42),
  display_name          VARCHAR(42),
  previous_display_name VARCHAR(42),
  trust_level           VARCHAR(42),
  previous_trust_level  VARCHAR(42),
  friend_number         VARCHAR(42)
);

CREATE TABLE GAMELOG_JOIN_LEAVE (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  type         VARCHAR(42),
  display_name VARCHAR(42),
  location     VARCHAR(42),
  time         VARCHAR(42)
);

CREATE TABLE GAMELOG_LOCATION (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  location   VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42) NOT NULL
);

CREATE TABLE HAS_AVATAR (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE HAS_BIO (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE HAS_STATUS (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE IS_ONLINE (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE JOIN_BY (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE LOGGED (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE MEMO (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  user_id   VARCHAR(42) NOT NULL
);

CREATE TABLE MODERATION (
  PRIMARY KEY (updated_at),
  updated_at   VARCHAR(42) NOT NULL,
  display_name VARCHAR(42),
  block        VARCHAR(42),
  mute         VARCHAR(42),
  user_id      VARCHAR(42) NOT NULL
);

CREATE TABLE MUTUAL_GRAPH_FRIEND_OLD (
  PRIMARY KEY (friend_id),
  friend_id    VARCHAR(42) NOT NULL,
  last_updated VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_LINK (
  PRIMARY KEY (friend_id_1, friend_id_2),
  friend_id_1 VARCHAR(42) NOT NULL,
  friend_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE MUTUAL_GRAPH_LINK_OLD (
  PRIMARY KEY (friend_id_1, friend_id_2),
  friend_id_1 VARCHAR(42) NOT NULL,
  friend_id_2 VARCHAR(42) NOT NULL,
  date        VARCHAR(42)
);

CREATE TABLE NOTES (
  PRIMARY KEY (note),
  note       VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  user_id    VARCHAR(42) NOT NULL
);

CREATE TABLE NOTIFICATION (
  PRIMARY KEY (id),
  id               VARCHAR(42) NOT NULL,
  created_at       VARCHAR(42),
  type             VARCHAR(42),
  message          VARCHAR(42),
  world_name       VARCHAR(42),
  image_url        VARCHAR(42),
  invite_message   VARCHAR(42),
  request_message  VARCHAR(42),
  response_message VARCHAR(42),
  expired          VARCHAR(42),
  user_id_1        VARCHAR(42) NOT NULL,
  sender_username  VARCHAR(42),
  user_id_2        VARCHAR(42) NOT NULL,
  receiver_user_id VARCHAR(42)
);

CREATE TABLE POSTED (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE TAGGED (
  PRIMARY KEY (avatar_id, tag),
  avatar_id VARCHAR(42) NOT NULL,
  tag       VARCHAR(42) NOT NULL
);

CREATE TABLE USER (
  PRIMARY KEY (user_id),
  user_id       VARCHAR(42) NOT NULL,
  display_name  VARCHAR(42),
  trust_level   VARCHAR(42),
  friend_number VARCHAR(42)
);

CREATE TABLE WORLD (
  PRIMARY KEY (world_id),
  world_id            VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  description         VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE WORLD_MEMO (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  world_id  VARCHAR(42) NOT NULL
);

ALTER TABLE ACTIVITY_SESSION ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE AVATAR_MEMO ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (avatar_id);

ALTER TABLE FAVORITE_AVATAR ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (avatar_id);

ALTER TABLE FAVORITE_WORLD ADD FOREIGN KEY (world_id) REFERENCES WORLD (world_id);

ALTER TABLE FAV_FRIEND_OF ADD FOREIGN KEY (id) REFERENCES FAVORITE_FRIEND (id);
ALTER TABLE FAV_FRIEND_OF ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE GAMELOG_LOCATION ADD FOREIGN KEY (world_id) REFERENCES WORLD (world_id);

ALTER TABLE HAS_AVATAR ADD FOREIGN KEY (id) REFERENCES FEED_AVATAR (id);
ALTER TABLE HAS_AVATAR ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE HAS_BIO ADD FOREIGN KEY (id) REFERENCES FEED_BIO (id);
ALTER TABLE HAS_BIO ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE HAS_STATUS ADD FOREIGN KEY (id) REFERENCES FEED_STATUS (id);
ALTER TABLE HAS_STATUS ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE IS_ONLINE ADD FOREIGN KEY (id) REFERENCES FEED_ONLINE_OFFLINE (id);
ALTER TABLE IS_ONLINE ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE JOIN_BY ADD FOREIGN KEY (id) REFERENCES GAMELOG_JOIN_LEAVE (id);
ALTER TABLE JOIN_BY ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE LOGGED ADD FOREIGN KEY (id) REFERENCES FRIEND_LOG_HISTORY (id);
ALTER TABLE LOGGED ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE MEMO ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE MODERATION ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE MUTUAL_GRAPH_LINK_OLD ADD FOREIGN KEY (friend_id_2) REFERENCES MUTUAL_GRAPH_FRIEND_OLD (friend_id);
ALTER TABLE MUTUAL_GRAPH_LINK_OLD ADD FOREIGN KEY (friend_id_1) REFERENCES MUTUAL_GRAPH_FRIEND_OLD (friend_id);

ALTER TABLE NOTES ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE NOTIFICATION ADD FOREIGN KEY (user_id_2) REFERENCES USER (user_id);
ALTER TABLE NOTIFICATION ADD FOREIGN KEY (user_id_1) REFERENCES USER (user_id);

ALTER TABLE POSTED ADD FOREIGN KEY (id) REFERENCES FEED_GPS (id);
ALTER TABLE POSTED ADD FOREIGN KEY (user_id) REFERENCES USER (user_id);

ALTER TABLE TAGGED ADD FOREIGN KEY (tag) REFERENCES AVATAR_TAG (tag);
ALTER TABLE TAGGED ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (avatar_id);

ALTER TABLE WORLD_MEMO ADD FOREIGN KEY (world_id) REFERENCES WORLD (world_id);
